
ctl:
  plugins:
    - type: changelog
      name: changelog

    - name: this_repo
      type: git
      config:
        branch: main
        repo_url: git@github.com:20c/ctl.git

    - name: version
      type: version
      config:
        branch_dev: main
        branch_release: main
        repositories:
          - this_repo

  permissions:
    - namespace: "ctl"
      permission: "crud"

  log:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    loggers:
      ctl:
        handlers: [console]
        level: DEBUG
        propagate: no
      ctl.plugins.git:
        handlers: [console]
        level: DEBUG
        propagate: no
      usage:
        handlers: [console]
        level: INFO
        propagate: no
